const movies = [
  {
    id: 1,
    title: "Stree 2",
    year: 2024,
    genre: "Comedy Horror",
    rating: 7.5,
    director: "Amar Kaushik",
    language: "Hindi",
    duration: "2h 29m",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9aR-j0zyWwEQCIcULwDX_xWVZUmgApUhmLb_CLHMbHQ&s=10",
  },
  {
    id: 2,
    title: "12th Fail",
    year: 2023,
    genre: "Drama",
    rating: 9.0,
    director: "Vidhu Vinod Chopra",
    language: "Hindi",
    duration: "2h 26m",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgtVycKOGakMUuYIidMyVkY09v39SyLSpSdxc9G8-CQ&s=10",
  },
  {
    id: 3,
    title: "Laapataa Ladies",
    year: 2024,
    genre: "Comedy Drama",
    rating: 8.4,
    director: "Kiran Rao",
    language: "Hindi",
    duration: "2h 4m",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTUs0mOuC7KzyaX2ZaHkYh2uss6Hdx8kLnk_57k5asEw&s=10",
  },
  {
    id: 4,
    title: "Fighter",
    year: 2024,
    genre: "Action",
    rating: 6.4,
    director: "Siddharth Anand",
    language: "Hindi",
    duration: "2h 46m",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDt1bOdJrgWKg-mIJ3pENHMeotaKzs3mLtth_JVVQiOQ&s=10",
  },
  {
    id: 5,
    title: "Crew",
    year: 2024,
    genre: "Comedy",
    rating: 6.3,
    director: "Rajesh A. Krishnan",
    language: "Hindi",
    duration: "2h 4m",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbK1s2mwd7VzLLt3UbCKq_QAO8zDKswYo4YiHpTpbqQg&s=10",
  },
  {
    id: 6,
    title: "Animal",
    year: 2023,
    genre: "Action Drama",
    rating: 6.2,
    director: "Sandeep Reddy Vanga",
    language: "Hindi",
    duration: "3h 21m",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjE0esfM-HjK8ahPGL_gYahqRM_K2dTNHDdDEfRD70tw&s=10",
  },
  {
    id: 7,
    title: "Munjya",
    year: 2024,
    genre: "Comedy Horror",
    rating: 6.8,
    director: "Aditya Sarpotdar",
    language: "Hindi",
    duration: "2h 3m",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrlAMYpjkdAZZ4YcsMyQ43-WP_Z3MCGHwiEWdvoTmTOw&s=10",
  },
  {
    id: 8,
    title: "Chandu Champion",
    year: 2024,
    genre: "Sports Drama",
    rating: 7.9,
    director: "Kabir Khan",
    language: "Hindi",
    duration: "2h 23m",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2ynd0I4WuFSGxACFADiL3u4r34Xyep-cVTavUXxvDdg&s=10",
  },
];

export default movies;